version: "3.9"

services:
  backend:
    image: node:16.15
    container_name: backend
    build: ./
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/template

  mongodb:
    image: mongo:5.0.7
    container_name: database
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: template_net


